level01.자연수 뒤집어 배열로 만들기
Mirim-Study/Algorithm pull request #21
Opened 2020-08-25 13:20 UTC by areumsheep

for문을 쓰는 건 좀 아닌 것 같은데 다른 방법 아시나요..?

2020-08-26 00:08 UTC, yoojinhee03 requested changes

2020-08-26 00:08 UTC, yoojinhee03 commented on programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/areum.js
> +    }
n=n.split('').reverse().map(parseFloat); 이걸로 한번 해보세요!

2020-08-26 00:12 UTC, yoojinhee03 requested changes

2020-08-26 00:12 UTC, yoojinhee03 commented on programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/areum.js
> +    }
```suggestion
     n=n.split('').reverse().map(parseFloat);
```
이렇게 한번 해보실래요??

2020-08-27 00:07 UTC, areumsheep commented on programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/areum.js
> +    }
map이 뭔지 모르겠는데 설명 가능하신가요..?

2020-08-27 08:52 UTC, yoojinhee03 commented on programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/areum.js
> +    }
https://velog.io/@daybreak/Javascript-map%ED%95%A8%EC%88%98 참고하세요!

2020-08-27 14:08 UTC, areumsheep commented on programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/areum.js
> +    }
오 감사합니다! 유용한 글이네요👍

2020-08-27 14:09 UTC, merged