Suhyeon
Mirim-Study/Algorithm pull request #23
Opened 2020-08-26 12:11 UTC by wander0220

2020-08-26 12:39 UTC, yoojinhee03 requested changes

2020-08-26 12:39 UTC, yoojinhee03 commented on programmers/난이도별/level01.약수의_합/wander0220.js
> +    return sum;
```suggestion
    for(var i = 1 ; i <= n/2 ; i++){
        if(n%i==0) sum+=i;
    }
    
    return sum+n;
```
이렇게 하면 더 효율적일것 같아요!!

2020-08-26 23:37 UTC, wander0220 commented on programmers/난이도별/level01.약수의_합/wander0220.js
> +    return sum;
오~~ 감사합니다!

2020-08-27 00:04 UTC, areumsheep approved these changes

2020-08-27 08:51 UTC, yoojinhee03 approved these changes

2020-08-28 02:39 UTC, merged