level 01.문자열 내 p와 y의 개수
Mirim-Study/Algorithm pull request #429
Opened 2022-02-06 15:05 UTC by Moon-HyeKyung

2022/02/07
https://programmers.co.kr/learn/courses/30/lessons/12916

2022-02-06 15:16 UTC, pppeum62 requested changes
모든 테스트케이스를 통과하는 코드가 맞나요?🤔

2022-02-06 15:20 UTC, Moon-HyeKyung commented
> 모든 테스트케이스를 통과하는 코드가 맞나요?🤔
넵
![image](https://user-images.githubusercontent.com/75727995/152687815-78a0a14e-224d-4d29-9a44-7aebaa0402c6.png)

2022-02-06 15:27 UTC, Moon-HyeKyung commented
> > 모든 테스트케이스를 통과하는 코드가 맞나요?🤔
추가로 설명드리자면
1. `s.split('')` 을 통해 각 문자를 배열에 담는다.
2. reduce 함수[reduce(callback함수, accumulator의 초기값)]를 통해 accumulator의 초기값은 0으로 세팅하고, 현재 배열의 값이 p일 경우 accumulator에 +1, y일 경우 -1를 합니다.
```
 reduce((accumulator, currentValue) => {
 // 문자 p일 경우 +1, y일 경우 -1
 }, 0)
``` 
3. p와 y의 개수가 동일할 경우 0을 리턴합니다.

2022-02-06 15:33 UTC, pppeum62 commented
> > > 모든 테스트케이스를 통과하는 코드가 맞나요?🤔
> 
> 추가로 설명드리자면
> 
> 1. `s.split('')` 을 통해 각 문자를 배열에 담는다.
> 2. reduce 함수[reduce(callback함수, accumulator의 초기값)]를 통해 accumulator의 초기값은 0으로 세팅하고, 현재 배열의 값이 p일 경우 accumulator에 +1, y일 경우 -1를 합니다. (https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce << **참고**)
> 
> ```
>  reduce((accumulator, currentValue) => {
>  // 문자 p일 경우 +1, y일 경우 -1
>  }, 0)
> ```
> 
> 3. p와 y의 개수가 동일할 경우 0을 리턴합니다.

그렇군용 설명 감사합니다👍 
프로그래머스 테스트 3번 기댓값이 잘못 세팅된 거였네요...! ㅠㅠ

2022-02-06 15:33 UTC, pppeum62 approved these changes

2022-02-08 05:56 UTC, Moon-HyeKyung commented
엇? 기쁨님이 따로 등록하신 테스트케이스 인가요? 아니면 프로그래머스 자체인가요?

2022-02-08 05:59 UTC, pppeum62 commented
> 엇? 기쁨님이 따로 등록하신 테스트케이스 인가요? 아니면 프로그래머스 자체인가요?

프로그래머스에 등록되어 있는 테스트요
`제출 후 채점하기`에 등록된 테스트 말고 `코드 실행`에 등록된 테스트 3번이용

2022-02-08 10:18 UTC, areumsheep approved these changes

2022-02-08 10:23 UTC, areumsheep commented
```javascript
function solution(s){   
    var answer = (s.match(/p/ig)|| []).length == (s.match(/y/ig)|| []).length;
    return answer;
}
```
저도 기쁨님께서 달아주신 댓글 보고 링크 들어가보니까 위처럼 작성했던 기록이 있네요~ 정규식을 활용하는 것도 하나의 방법 같아요!
좋은 코드, 설명 잘 보고 갑니당💪

2022-02-08 14:34 UTC, Moon-HyeKyung commented
@pppeum62  기쁨님! `코드 실행`의 테스트 케이스 3번은 없습니다! 혹시 기쁨님이 추가하신 건 아닌지요?ㅎㅎ

2022-02-09 08:56 UTC, pppeum62 commented
> @pppeum62 기쁨님! `코드 실행`의 테스트 케이스 3번은 없습니다! 혹시 기쁨님이 추가하신 건 아닌지요?ㅎㅎ

헉... 제가 모바일로 확인을 해서 프로그래머스 자체 테스트라고 착각했네요...!! 죄송합니다 ㅠㅠㅜ

2022-02-09 09:00 UTC, pppeum62 commented
> ```js
> function solution(s){   
>     var answer = (s.match(/p/ig)|| []).length == (s.match(/y/ig)|| []).length;
>     return answer;
> }
> ```
> 
> 저도 기쁨님께서 달아주신 댓글 보고 링크 들어가보니까 위처럼 작성했던 기록이 있네요~(다른 분 코드 참고한 것 같아요) 정규식을 활용하는 것도 하나의 방법 같습니당 `/ig` > 대소문자 구분 없이 전체 단어 확인해서 찾는 정규식이네요 (https://blog.outsider.ne.kr/141)
> 
> **좋은 코드, 설명** 잘 보고 갑니당💪

대소문자 구분은 `toLowerCase()`나 `toUpperCase()`를 사용할 수도 있을 거 같아요!!

2022-03-21 15:31 UTC, merged